# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/otus_homework_7/otus_homework_7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/otus_homework_7/otus_homework_7

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/runner/work/otus_homework_7/otus_homework_7/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_homework_7/otus_homework_7/CMakeFiles /home/runner/work/otus_homework_7/otus_homework_7//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_homework_7/otus_homework_7/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc_doxygen.dir/build.make CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

#=============================================================================
# Target rules for targets named bayan

# Build rule for target.
bayan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bayan
.PHONY : bayan

# fast build rule for target.
bayan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/build
.PHONY : bayan/fast

#=============================================================================
# Target rules for targets named bayan_lib

# Build rule for target.
bayan_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bayan_lib
.PHONY : bayan_lib

# fast build rule for target.
bayan_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan_lib.dir/build.make CMakeFiles/bayan_lib.dir/build
.PHONY : bayan_lib/fast

#=============================================================================
# Target rules for targets named test_Version

# Build rule for target.
test_Version: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Version
.PHONY : test_Version

# fast build rule for target.
test_Version/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Version.dir/build.make CMakeFiles/test_Version.dir/build
.PHONY : test_Version/fast

#=============================================================================
# Target rules for targets named test_hash_processor

# Build rule for target.
test_hash_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hash_processor
.PHONY : test_hash_processor

# fast build rule for target.
test_hash_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash_processor.dir/build.make CMakeFiles/test_hash_processor.dir/build
.PHONY : test_hash_processor/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/test_hash_processor.o: src/test_hash_processor.cpp.o
.PHONY : src/test_hash_processor.o

# target to build an object file
src/test_hash_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash_processor.dir/build.make CMakeFiles/test_hash_processor.dir/src/test_hash_processor.cpp.o
.PHONY : src/test_hash_processor.cpp.o

src/test_hash_processor.i: src/test_hash_processor.cpp.i
.PHONY : src/test_hash_processor.i

# target to preprocess a source file
src/test_hash_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash_processor.dir/build.make CMakeFiles/test_hash_processor.dir/src/test_hash_processor.cpp.i
.PHONY : src/test_hash_processor.cpp.i

src/test_hash_processor.s: src/test_hash_processor.cpp.s
.PHONY : src/test_hash_processor.s

# target to generate assembly for a file
src/test_hash_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash_processor.dir/build.make CMakeFiles/test_hash_processor.dir/src/test_hash_processor.cpp.s
.PHONY : src/test_hash_processor.cpp.s

src/version/test_Version.o: src/version/test_Version.cpp.o
.PHONY : src/version/test_Version.o

# target to build an object file
src/version/test_Version.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Version.dir/build.make CMakeFiles/test_Version.dir/src/version/test_Version.cpp.o
.PHONY : src/version/test_Version.cpp.o

src/version/test_Version.i: src/version/test_Version.cpp.i
.PHONY : src/version/test_Version.i

# target to preprocess a source file
src/version/test_Version.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Version.dir/build.make CMakeFiles/test_Version.dir/src/version/test_Version.cpp.i
.PHONY : src/version/test_Version.cpp.i

src/version/test_Version.s: src/version/test_Version.cpp.s
.PHONY : src/version/test_Version.s

# target to generate assembly for a file
src/version/test_Version.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Version.dir/build.make CMakeFiles/test_Version.dir/src/version/test_Version.cpp.s
.PHONY : src/version/test_Version.cpp.s

src/version/versionLib.o: src/version/versionLib.cpp.o
.PHONY : src/version/versionLib.o

# target to build an object file
src/version/versionLib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan_lib.dir/build.make CMakeFiles/bayan_lib.dir/src/version/versionLib.cpp.o
.PHONY : src/version/versionLib.cpp.o

src/version/versionLib.i: src/version/versionLib.cpp.i
.PHONY : src/version/versionLib.i

# target to preprocess a source file
src/version/versionLib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan_lib.dir/build.make CMakeFiles/bayan_lib.dir/src/version/versionLib.cpp.i
.PHONY : src/version/versionLib.cpp.i

src/version/versionLib.s: src/version/versionLib.cpp.s
.PHONY : src/version/versionLib.s

# target to generate assembly for a file
src/version/versionLib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan_lib.dir/build.make CMakeFiles/bayan_lib.dir/src/version/versionLib.cpp.s
.PHONY : src/version/versionLib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... doc_doxygen"
	@echo "... bayan"
	@echo "... bayan_lib"
	@echo "... test_Version"
	@echo "... test_hash_processor"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test_hash_processor.o"
	@echo "... src/test_hash_processor.i"
	@echo "... src/test_hash_processor.s"
	@echo "... src/version/test_Version.o"
	@echo "... src/version/test_Version.i"
	@echo "... src/version/test_Version.s"
	@echo "... src/version/versionLib.o"
	@echo "... src/version/versionLib.i"
	@echo "... src/version/versionLib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

